# Generated by Django 4.0 on 2021-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211219_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='descirption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
